-- Industrial KPI model for a fictional multi-site manufacturing platform.
-- This script is idempotent and can be executed multiple times safely.

BEGIN;

CREATE SCHEMA IF NOT EXISTS analytics;

-- Keep updated_at consistent without relying on every application client.
CREATE OR REPLACE FUNCTION analytics.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- Manufacturing sites managed by the platform.
CREATE TABLE IF NOT EXISTS analytics.dim_sites (
    site_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_code VARCHAR(20) NOT NULL,
    site_name VARCHAR(120) NOT NULL,
    country_code CHAR(2) NOT NULL,
    city VARCHAR(100) NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    commissioned_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT dim_sites_site_code_key UNIQUE (site_code),
    CONSTRAINT dim_sites_status_check
        CHECK (status IN ('active', 'maintenance', 'inactive')),
    CONSTRAINT dim_sites_country_code_check
        CHECK (country_code ~ '^[A-Z]{2}$')
);

COMMENT ON TABLE analytics.dim_sites IS
    'Reference data for manufacturing sites monitored by the platform.';
COMMENT ON COLUMN analytics.dim_sites.site_code IS
    'Stable business identifier used by source systems.';
COMMENT ON COLUMN analytics.dim_sites.timezone IS
    'IANA timezone used to interpret site-local operational timestamps.';

-- Products manufactured across one or more sites.
CREATE TABLE IF NOT EXISTS analytics.dim_products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(30) NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    product_family VARCHAR(80) NOT NULL,
    unit_of_measure VARCHAR(20) NOT NULL DEFAULT 'unit',
    standard_cycle_time_seconds NUMERIC(10, 2) NOT NULL,
    target_scrap_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT dim_products_product_code_key UNIQUE (product_code),
    CONSTRAINT dim_products_cycle_time_check
        CHECK (standard_cycle_time_seconds > 0),
    CONSTRAINT dim_products_scrap_rate_check
        CHECK (target_scrap_rate BETWEEN 0 AND 100)
);

COMMENT ON TABLE analytics.dim_products IS
    'Product master data and reference targets used to calculate KPIs.';
COMMENT ON COLUMN analytics.dim_products.target_scrap_rate IS
    'Maximum expected scrap rate expressed as a percentage.';

-- Production execution facts at work-order level.
CREATE TABLE IF NOT EXISTS analytics.fact_production_orders (
    production_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40) NOT NULL,
    site_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    line_code VARCHAR(30) NOT NULL,
    order_status VARCHAR(20) NOT NULL DEFAULT 'planned',
    planned_quantity INTEGER NOT NULL,
    produced_quantity INTEGER NOT NULL DEFAULT 0,
    rejected_quantity INTEGER NOT NULL DEFAULT 0,
    planned_start_at TIMESTAMPTZ NOT NULL,
    planned_end_at TIMESTAMPTZ NOT NULL,
    actual_start_at TIMESTAMPTZ,
    actual_end_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fact_production_orders_order_number_key
        UNIQUE (order_number),
    CONSTRAINT fact_production_orders_site_fk
        FOREIGN KEY (site_id)
        REFERENCES analytics.dim_sites (site_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fact_production_orders_product_fk
        FOREIGN KEY (product_id)
        REFERENCES analytics.dim_products (product_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fact_production_orders_status_check
        CHECK (
            order_status IN (
                'planned',
                'in_progress',
                'completed',
                'cancelled'
            )
        ),
    CONSTRAINT fact_production_orders_planned_quantity_check
        CHECK (planned_quantity > 0),
    CONSTRAINT fact_production_orders_produced_quantity_check
        CHECK (produced_quantity >= 0),
    CONSTRAINT fact_production_orders_rejected_quantity_check
        CHECK (
            rejected_quantity >= 0
            AND rejected_quantity <= produced_quantity
        ),
    CONSTRAINT fact_production_orders_planned_dates_check
        CHECK (planned_end_at > planned_start_at),
    CONSTRAINT fact_production_orders_actual_dates_check
        CHECK (
            actual_end_at IS NULL
            OR (
                actual_start_at IS NOT NULL
                AND actual_end_at >= actual_start_at
            )
        )
);

COMMENT ON TABLE analytics.fact_production_orders IS
    'Production quantities and schedule execution at work-order level.';
COMMENT ON COLUMN analytics.fact_production_orders.rejected_quantity IS
    'Quantity rejected during production; it is included in produced_quantity.';

-- Quality inspection facts linked to production orders.
CREATE TABLE IF NOT EXISTS analytics.fact_quality_controls (
    quality_control_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_reference VARCHAR(50) NOT NULL,
    production_order_id BIGINT NOT NULL,
    controlled_at TIMESTAMPTZ NOT NULL,
    sample_size INTEGER NOT NULL,
    passed_quantity INTEGER NOT NULL DEFAULT 0,
    failed_quantity INTEGER NOT NULL DEFAULT 0,
    result VARCHAR(20) NOT NULL,
    defect_category VARCHAR(80),
    inspector_name VARCHAR(120) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fact_quality_controls_reference_key
        UNIQUE (control_reference),
    CONSTRAINT fact_quality_controls_order_fk
        FOREIGN KEY (production_order_id)
        REFERENCES analytics.fact_production_orders (production_order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fact_quality_controls_sample_size_check
        CHECK (sample_size > 0),
    CONSTRAINT fact_quality_controls_quantities_check
        CHECK (
            passed_quantity >= 0
            AND failed_quantity >= 0
            AND passed_quantity + failed_quantity <= sample_size
        ),
    CONSTRAINT fact_quality_controls_result_check
        CHECK (result IN ('passed', 'warning', 'failed')),
    CONSTRAINT fact_quality_controls_defect_check
        CHECK (
            failed_quantity = 0
            OR defect_category IS NOT NULL
        )
);

COMMENT ON TABLE analytics.fact_quality_controls IS
    'Quality samples and inspection outcomes for production orders.';

-- Traceability for CSV, API and ETL imports.
CREATE TABLE IF NOT EXISTS analytics.import_logs (
    import_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_reference VARCHAR(60) NOT NULL,
    source_system VARCHAR(80) NOT NULL,
    source_file VARCHAR(255),
    import_status VARCHAR(20) NOT NULL,
    rows_received INTEGER NOT NULL DEFAULT 0,
    rows_processed INTEGER NOT NULL DEFAULT 0,
    rows_rejected INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT import_logs_reference_key UNIQUE (import_reference),
    CONSTRAINT import_logs_status_check
        CHECK (import_status IN ('running', 'completed', 'partial', 'failed')),
    CONSTRAINT import_logs_row_counts_check
        CHECK (
            rows_received >= 0
            AND rows_processed >= 0
            AND rows_rejected >= 0
            AND rows_processed + rows_rejected <= rows_received
        ),
    CONSTRAINT import_logs_dates_check
        CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT import_logs_completion_check
        CHECK (
            (import_status = 'running' AND completed_at IS NULL)
            OR (import_status <> 'running' AND completed_at IS NOT NULL)
        )
);

COMMENT ON TABLE analytics.import_logs IS
    'Operational audit trail for data imports and their row-level outcomes.';

-- Foreign-key indexes improve joins and cascading integrity checks.
CREATE INDEX IF NOT EXISTS fact_production_orders_site_id_idx
    ON analytics.fact_production_orders (site_id);

CREATE INDEX IF NOT EXISTS fact_production_orders_product_id_idx
    ON analytics.fact_production_orders (product_id);

CREATE INDEX IF NOT EXISTS fact_production_orders_site_start_idx
    ON analytics.fact_production_orders (site_id, planned_start_at DESC);

CREATE INDEX IF NOT EXISTS fact_production_orders_status_idx
    ON analytics.fact_production_orders (order_status)
    WHERE order_status IN ('planned', 'in_progress');

CREATE INDEX IF NOT EXISTS fact_quality_controls_order_id_idx
    ON analytics.fact_quality_controls (production_order_id);

CREATE INDEX IF NOT EXISTS fact_quality_controls_controlled_at_idx
    ON analytics.fact_quality_controls (controlled_at DESC);

CREATE INDEX IF NOT EXISTS fact_quality_controls_failed_idx
    ON analytics.fact_quality_controls (production_order_id, controlled_at DESC)
    WHERE failed_quantity > 0;

CREATE INDEX IF NOT EXISTS import_logs_started_at_idx
    ON analytics.import_logs (started_at DESC);

CREATE INDEX IF NOT EXISTS import_logs_status_idx
    ON analytics.import_logs (import_status)
    WHERE import_status IN ('running', 'partial', 'failed');

-- Recreate triggers so this script remains safe after function changes.
DROP TRIGGER IF EXISTS dim_sites_set_updated_at
    ON analytics.dim_sites;
CREATE TRIGGER dim_sites_set_updated_at
BEFORE UPDATE ON analytics.dim_sites
FOR EACH ROW
EXECUTE FUNCTION analytics.set_updated_at();

DROP TRIGGER IF EXISTS dim_products_set_updated_at
    ON analytics.dim_products;
CREATE TRIGGER dim_products_set_updated_at
BEFORE UPDATE ON analytics.dim_products
FOR EACH ROW
EXECUTE FUNCTION analytics.set_updated_at();

DROP TRIGGER IF EXISTS fact_production_orders_set_updated_at
    ON analytics.fact_production_orders;
CREATE TRIGGER fact_production_orders_set_updated_at
BEFORE UPDATE ON analytics.fact_production_orders
FOR EACH ROW
EXECUTE FUNCTION analytics.set_updated_at();

DROP TRIGGER IF EXISTS fact_quality_controls_set_updated_at
    ON analytics.fact_quality_controls;
CREATE TRIGGER fact_quality_controls_set_updated_at
BEFORE UPDATE ON analytics.fact_quality_controls
FOR EACH ROW
EXECUTE FUNCTION analytics.set_updated_at();

DROP TRIGGER IF EXISTS import_logs_set_updated_at
    ON analytics.import_logs;
CREATE TRIGGER import_logs_set_updated_at
BEFORE UPDATE ON analytics.import_logs
FOR EACH ROW
EXECUTE FUNCTION analytics.set_updated_at();

COMMIT;
